# Generated by Django 3.0.4 on 2020-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_subtitle', models.CharField(max_length=20)),
                ('item_desc', models.CharField(max_length=900)),
                ('item_image', models.CharField(default='https://anvilhotel.com/wp-content/uploads/2017/08/food-placeholder.png', max_length=500)),
            ],
        ),
    ]
